# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

# Do not build tags; it is redundant.
if: tag IS blank

# https://docs.travis-ci.com/user/docker/
sudo: required

services:
  - docker

script:
  - ./test.sh
